# syntax=docker/dockerfile:1.4
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    firefox-esr wget xvfb tar libpq-dev gcc git \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz \
    && tar -xvzf geckodriver-v0.36.0-linux64.tar.gz \
    && mv geckodriver /usr/local/bin/ \
    && chmod +x /usr/local/bin/geckodriver \
    && rm geckodriver-v0.36.0-linux64.tar.gz

ENV DISPLAY=:99
WORKDIR /bot

COPY requirements.txt .

RUN --mount=type=secret,id=github_token \
    cp requirements.txt temp-requirements.txt && \
    sed -i "s|\${GITHUB_TOKEN}|$(cat /run/secrets/github_token)|g" temp-requirements.txt && \
    pip install --no-cache-dir -r temp-requirements.txt && \
    rm temp-requirements.txt

COPY config /bot/config/
COPY logger /bot/logger/
COPY src /bot/src/
COPY main.py /bot/main.py
# COPY .env .env # just for local development

ENV PYTHONPATH=/bot

CMD ["python", "main.py"]
