[project]
name = "etv-course-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "db-handler",
    "selenium==4.44.0",
    "python-dotenv==1.2.2",
    "pandas==3.0.3",
    "SQLAlchemy==2.0.49",
    "psycopg2==2.9.12",
    "pycparser==3.0",
    "pydantic==2.13.4",
]

[tool.uv.sources]
db-handler = { git = "https://github.com/pgreis/etv_course_db.git", rev = "v0.1.0" }